// Enhanced Currency interface with full metadata
export interface Currency {
  code: string; // ISO 4217 code
  symbol: string; // Primary symbol
  symbolNative?: string; // Native script symbol (if different)
  name: string; // English name
  namePlural: string; // Plural form
  decimalDigits: number; // Number of decimal places
  rounding: number; // Rounding increment
  locale: string; // BCP 47 locale code
  symbolPosition: "before" | "after"; // Symbol placement
  spaceBetween: boolean; // Space between symbol and amount
}

// Comprehensive list of 150+ global currencies
export const CURRENCIES: Currency[] = [
  // Popular/Major Currencies (sorted alphabetically)
  {
    code: "AED",
    symbol: "د.إ",
    name: "UAE Dirham",
    namePlural: "UAE dirhams",
    decimalDigits: 2,
    rounding: 0,
    locale: "ar-AE",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "AFN",
    symbol: "؋",
    name: "Afghan Afghani",
    namePlural: "Afghan Afghanis",
    decimalDigits: 0,
    rounding: 0,
    locale: "fa-AF",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "ALL",
    symbol: "L",
    name: "Albanian Lek",
    namePlural: "Albanian lekë",
    decimalDigits: 0,
    rounding: 0,
    locale: "sq-AL",
    symbolPosition: "after",
    spaceBetween: true,
  },
  {
    code: "AMD",
    symbol: "֏",
    name: "Armenian Dram",
    namePlural: "Armenian drams",
    decimalDigits: 0,
    rounding: 0,
    locale: "hy-AM",
    symbolPosition: "after",
    spaceBetween: true,
  },
  {
    code: "ANG",
    symbol: "ƒ",
    name: "Netherlands Antillean Guilder",
    namePlural: "Netherlands Antillean guilders",
    decimalDigits: 2,
    rounding: 0,
    locale: "nl-AN",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "AOA",
    symbol: "Kz",
    name: "Angolan Kwanza",
    namePlural: "Angolan kwanzas",
    decimalDigits: 2,
    rounding: 0,
    locale: "pt-AO",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "ARS",
    symbol: "$",
    name: "Argentine Peso",
    namePlural: "Argentine pesos",
    decimalDigits: 2,
    rounding: 0,
    locale: "es-AR",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "AUD",
    symbol: "A$",
    name: "Australian Dollar",
    namePlural: "Australian dollars",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-AU",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "AWG",
    symbol: "ƒ",
    name: "Aruban Florin",
    namePlural: "Aruban florin",
    decimalDigits: 2,
    rounding: 0,
    locale: "nl-AW",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "AZN",
    symbol: "₼",
    name: "Azerbaijani Manat",
    namePlural: "Azerbaijani manats",
    decimalDigits: 2,
    rounding: 0,
    locale: "az-AZ",
    symbolPosition: "before",
    spaceBetween: true,
  },

  {
    code: "BAM",
    symbol: "KM",
    name: "Bosnia-Herzegovina Convertible Mark",
    namePlural: "Bosnia-Herzegovina convertible marks",
    decimalDigits: 2,
    rounding: 0,
    locale: "bs-BA",
    symbolPosition: "after",
    spaceBetween: true,
  },
  {
    code: "BBD",
    symbol: "$",
    name: "Barbadian Dollar",
    namePlural: "Barbadian dollars",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-BB",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "BDT",
    symbol: "৳",
    name: "Bangladeshi Taka",
    namePlural: "Bangladeshi takas",
    decimalDigits: 2,
    rounding: 0,
    locale: "bn-BD",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "BGN",
    symbol: "лв",
    name: "Bulgarian Lev",
    namePlural: "Bulgarian leva",
    decimalDigits: 2,
    rounding: 0,
    locale: "bg-BG",
    symbolPosition: "after",
    spaceBetween: true,
  },
  {
    code: "BHD",
    symbol: "د.ب",
    name: "Bahraini Dinar",
    namePlural: "Bahraini dinars",
    decimalDigits: 3,
    rounding: 0,
    locale: "ar-BH",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "BIF",
    symbol: "FBu",
    name: "Burundian Franc",
    namePlural: "Burundian francs",
    decimalDigits: 0,
    rounding: 0,
    locale: "fr-BI",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "BMD",
    symbol: "$",
    name: "Bermudan Dollar",
    namePlural: "Bermudan dollars",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-BM",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "BND",
    symbol: "$",
    name: "Brunei Dollar",
    namePlural: "Brunei dollars",
    decimalDigits: 2,
    rounding: 0,
    locale: "ms-BN",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "BOB",
    symbol: "Bs",
    name: "Bolivian Boliviano",
    namePlural: "Bolivian bolivianos",
    decimalDigits: 2,
    rounding: 0,
    locale: "es-BO",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "BRL",
    symbol: "R$",
    name: "Brazilian Real",
    namePlural: "Brazilian reais",
    decimalDigits: 2,
    rounding: 0,
    locale: "pt-BR",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "BSD",
    symbol: "$",
    name: "Bahamian Dollar",
    namePlural: "Bahamian dollars",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-BS",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "BTN",
    symbol: "Nu.",
    name: "Bhutanese Ngultrum",
    namePlural: "Bhutanese ngultrums",
    decimalDigits: 2,
    rounding: 0,
    locale: "dz-BT",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "BWP",
    symbol: "P",
    name: "Botswanan Pula",
    namePlural: "Botswanan pulas",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-BW",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "BYN",
    symbol: "Br",
    name: "Belarusian Ruble",
    namePlural: "Belarusian rubles",
    decimalDigits: 2,
    rounding: 0,
    locale: "be-BY",
    symbolPosition: "after",
    spaceBetween: true,
  },
  {
    code: "BZD",
    symbol: "$",
    name: "Belize Dollar",
    namePlural: "Belize dollars",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-BZ",
    symbolPosition: "before",
    spaceBetween: false,
  },

  {
    code: "CAD",
    symbol: "C$",
    name: "Canadian Dollar",
    namePlural: "Canadian dollars",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-CA",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "CDF",
    symbol: "FC",
    name: "Congolese Franc",
    namePlural: "Congolese francs",
    decimalDigits: 2,
    rounding: 0,
    locale: "fr-CD",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "CHF",
    symbol: "Fr",
    name: "Swiss Franc",
    namePlural: "Swiss francs",
    decimalDigits: 2,
    rounding: 0.05,
    locale: "de-CH",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "CLP",
    symbol: "$",
    name: "Chilean Peso",
    namePlural: "Chilean pesos",
    decimalDigits: 0,
    rounding: 0,
    locale: "es-CL",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "CNY",
    symbol: "¥",
    symbolNative: "￥",
    name: "Chinese Yuan",
    namePlural: "Chinese yuan",
    decimalDigits: 2,
    rounding: 0,
    locale: "zh-CN",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "COP",
    symbol: "$",
    name: "Colombian Peso",
    namePlural: "Colombian pesos",
    decimalDigits: 0,
    rounding: 0,
    locale: "es-CO",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "CRC",
    symbol: "₡",
    name: "Costa Rican Colón",
    namePlural: "Costa Rican colóns",
    decimalDigits: 0,
    rounding: 0,
    locale: "es-CR",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "CUP",
    symbol: "$",
    name: "Cuban Peso",
    namePlural: "Cuban pesos",
    decimalDigits: 2,
    rounding: 0,
    locale: "es-CU",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "CVE",
    symbol: "$",
    name: "Cape Verdean Escudo",
    namePlural: "Cape Verdean escudos",
    decimalDigits: 2,
    rounding: 0,
    locale: "pt-CV",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "CZK",
    symbol: "Kč",
    name: "Czech Republic Koruna",
    namePlural: "Czech Republic korunas",
    decimalDigits: 2,
    rounding: 0,
    locale: "cs-CZ",
    symbolPosition: "after",
    spaceBetween: true,
  },

  {
    code: "DJF",
    symbol: "Fdj",
    name: "Djiboutian Franc",
    namePlural: "Djiboutian francs",
    decimalDigits: 0,
    rounding: 0,
    locale: "fr-DJ",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "DKK",
    symbol: "kr",
    name: "Danish Krone",
    namePlural: "Danish kroner",
    decimalDigits: 2,
    rounding: 0,
    locale: "da-DK",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "DOP",
    symbol: "$",
    name: "Dominican Peso",
    namePlural: "Dominican pesos",
    decimalDigits: 2,
    rounding: 0,
    locale: "es-DO",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "DZD",
    symbol: "د.ج",
    name: "Algerian Dinar",
    namePlural: "Algerian dinars",
    decimalDigits: 2,
    rounding: 0,
    locale: "ar-DZ",
    symbolPosition: "before",
    spaceBetween: true,
  },

  {
    code: "EGP",
    symbol: "E£",
    symbolNative: "ج.م",
    name: "Egyptian Pound",
    namePlural: "Egyptian pounds",
    decimalDigits: 2,
    rounding: 0,
    locale: "ar-EG",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "ERN",
    symbol: "Nfk",
    name: "Eritrean Nakfa",
    namePlural: "Eritrean nakfas",
    decimalDigits: 2,
    rounding: 0,
    locale: "ti-ER",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "ETB",
    symbol: "Br",
    name: "Ethiopian Birr",
    namePlural: "Ethiopian birrs",
    decimalDigits: 2,
    rounding: 0,
    locale: "am-ET",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "EUR",
    symbol: "€",
    name: "Euro",
    namePlural: "euros",
    decimalDigits: 2,
    rounding: 0,
    locale: "de-DE",
    symbolPosition: "before",
    spaceBetween: true,
  },

  {
    code: "FJD",
    symbol: "$",
    name: "Fijian Dollar",
    namePlural: "Fijian dollars",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-FJ",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "FKP",
    symbol: "£",
    name: "Falkland Islands Pound",
    namePlural: "Falkland Islands pounds",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-FK",
    symbolPosition: "before",
    spaceBetween: false,
  },

  {
    code: "GBP",
    symbol: "£",
    name: "British Pound Sterling",
    namePlural: "British pounds sterling",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-GB",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "GEL",
    symbol: "₾",
    name: "Georgian Lari",
    namePlural: "Georgian laris",
    decimalDigits: 2,
    rounding: 0,
    locale: "ka-GE",
    symbolPosition: "after",
    spaceBetween: true,
  },
  {
    code: "GHS",
    symbol: "GH₵",
    name: "Ghanaian Cedi",
    namePlural: "Ghanaian cedis",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-GH",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "GIP",
    symbol: "£",
    name: "Gibraltar Pound",
    namePlural: "Gibraltar pounds",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-GI",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "GMD",
    symbol: "D",
    name: "Gambian Dalasi",
    namePlural: "Gambian dalasis",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-GM",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "GNF",
    symbol: "FG",
    name: "Guinean Franc",
    namePlural: "Guinean francs",
    decimalDigits: 0,
    rounding: 0,
    locale: "fr-GN",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "GTQ",
    symbol: "Q",
    name: "Guatemalan Quetzal",
    namePlural: "Guatemalan quetzals",
    decimalDigits: 2,
    rounding: 0,
    locale: "es-GT",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "GYD",
    symbol: "$",
    name: "Guyanaese Dollar",
    namePlural: "Guyanaese dollars",
    decimalDigits: 0,
    rounding: 0,
    locale: "en-GY",
    symbolPosition: "before",
    spaceBetween: false,
  },

  {
    code: "HKD",
    symbol: "HK$",
    symbolNative: "港幣",
    name: "Hong Kong Dollar",
    namePlural: "Hong Kong dollars",
    decimalDigits: 2,
    rounding: 0,
    locale: "zh-HK",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "HNL",
    symbol: "L",
    name: "Honduran Lempira",
    namePlural: "Honduran lempiras",
    decimalDigits: 2,
    rounding: 0,
    locale: "es-HN",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "HRK",
    symbol: "kn",
    name: "Croatian Kuna",
    namePlural: "Croatian kunas",
    decimalDigits: 2,
    rounding: 0,
    locale: "hr-HR",
    symbolPosition: "after",
    spaceBetween: true,
  },
  {
    code: "HTG",
    symbol: "G",
    name: "Haitian Gourde",
    namePlural: "Haitian gourdes",
    decimalDigits: 2,
    rounding: 0,
    locale: "fr-HT",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "HUF",
    symbol: "Ft",
    name: "Hungarian Forint",
    namePlural: "Hungarian forints",
    decimalDigits: 0,
    rounding: 0,
    locale: "hu-HU",
    symbolPosition: "after",
    spaceBetween: true,
  },

  {
    code: "IDR",
    symbol: "Rp",
    name: "Indonesian Rupiah",
    namePlural: "Indonesian rupiahs",
    decimalDigits: 0,
    rounding: 0,
    locale: "id-ID",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "ILS",
    symbol: "₪",
    name: "Israeli New Sheqel",
    namePlural: "Israeli new sheqels",
    decimalDigits: 2,
    rounding: 0,
    locale: "he-IL",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "INR",
    symbol: "₹",
    symbolNative: "रु",
    name: "Indian Rupee",
    namePlural: "Indian rupees",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-IN",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "IQD",
    symbol: "ع.د",
    name: "Iraqi Dinar",
    namePlural: "Iraqi dinars",
    decimalDigits: 0,
    rounding: 0,
    locale: "ar-IQ",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "IRR",
    symbol: "﷼",
    name: "Iranian Rial",
    namePlural: "Iranian rials",
    decimalDigits: 0,
    rounding: 0,
    locale: "fa-IR",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "ISK",
    symbol: "kr",
    name: "Icelandic Króna",
    namePlural: "Icelandic krónur",
    decimalDigits: 0,
    rounding: 0,
    locale: "is-IS",
    symbolPosition: "after",
    spaceBetween: true,
  },

  {
    code: "JMD",
    symbol: "J$",
    name: "Jamaican Dollar",
    namePlural: "Jamaican dollars",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-JM",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "JOD",
    symbol: "د.ا",
    name: "Jordanian Dinar",
    namePlural: "Jordanian dinars",
    decimalDigits: 3,
    rounding: 0,
    locale: "ar-JO",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "JPY",
    symbol: "¥",
    symbolNative: "￥",
    name: "Japanese Yen",
    namePlural: "Japanese yen",
    decimalDigits: 0,
    rounding: 0,
    locale: "ja-JP",
    symbolPosition: "before",
    spaceBetween: false,
  },

  {
    code: "KES",
    symbol: "KSh",
    name: "Kenyan Shilling",
    namePlural: "Kenyan shillings",
    decimalDigits: 2,
    rounding: 0,
    locale: "sw-KE",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "KGS",
    symbol: "сом",
    name: "Kyrgystani Som",
    namePlural: "Kyrgystani soms",
    decimalDigits: 2,
    rounding: 0,
    locale: "ky-KG",
    symbolPosition: "after",
    spaceBetween: true,
  },
  {
    code: "KHR",
    symbol: "៛",
    name: "Cambodian Riel",
    namePlural: "Cambodian riels",
    decimalDigits: 2,
    rounding: 0,
    locale: "km-KH",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "KMF",
    symbol: "CF",
    name: "Comorian Franc",
    namePlural: "Comorian francs",
    decimalDigits: 0,
    rounding: 0,
    locale: "ar-KM",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "KPW",
    symbol: "₩",
    name: "North Korean Won",
    namePlural: "North Korean won",
    decimalDigits: 0,
    rounding: 0,
    locale: "ko-KP",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "KRW",
    symbol: "₩",
    symbolNative: "원",
    name: "South Korean Won",
    namePlural: "South Korean won",
    decimalDigits: 0,
    rounding: 0,
    locale: "ko-KR",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "KWD",
    symbol: "د.ك",
    name: "Kuwaiti Dinar",
    namePlural: "Kuwaiti dinars",
    decimalDigits: 3,
    rounding: 0,
    locale: "ar-KW",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "KYD",
    symbol: "$",
    name: "Cayman Islands Dollar",
    namePlural: "Cayman Islands dollars",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-KY",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "KZT",
    symbol: "₸",
    name: "Kazakhstani Tenge",
    namePlural: "Kazakhstani tenges",
    decimalDigits: 2,
    rounding: 0,
    locale: "kk-KZ",
    symbolPosition: "after",
    spaceBetween: true,
  },

  {
    code: "LAK",
    symbol: "₭",
    name: "Laotian Kip",
    namePlural: "Laotian kips",
    decimalDigits: 0,
    rounding: 0,
    locale: "lo-LA",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "LBP",
    symbol: "ل.ل",
    name: "Lebanese Pound",
    namePlural: "Lebanese pounds",
    decimalDigits: 0,
    rounding: 0,
    locale: "ar-LB",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "LKR",
    symbol: "Rs",
    symbolNative: "රු",
    name: "Sri Lankan Rupee",
    namePlural: "Sri Lankan rupees",
    decimalDigits: 2,
    rounding: 0,
    locale: "si-LK",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "LRD",
    symbol: "$",
    name: "Liberian Dollar",
    namePlural: "Liberian dollars",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-LR",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "LSL",
    symbol: "L",
    name: "Lesotho Loti",
    namePlural: "Lesotho lotis",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-LS",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "LYD",
    symbol: "ل.د",
    name: "Libyan Dinar",
    namePlural: "Libyan dinars",
    decimalDigits: 3,
    rounding: 0,
    locale: "ar-LY",
    symbolPosition: "before",
    spaceBetween: true,
  },

  {
    code: "MAD",
    symbol: "د.م.",
    name: "Moroccan Dirham",
    namePlural: "Moroccan dirhams",
    decimalDigits: 2,
    rounding: 0,
    locale: "ar-MA",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "MDL",
    symbol: "L",
    name: "Moldovan Leu",
    namePlural: "Moldovan lei",
    decimalDigits: 2,
    rounding: 0,
    locale: "ro-MD",
    symbolPosition: "after",
    spaceBetween: true,
  },
  {
    code: "MGA",
    symbol: "Ar",
    name: "Malagasy Ariary",
    namePlural: "Malagasy Ariaries",
    decimalDigits: 0,
    rounding: 0,
    locale: "mg-MG",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "MKD",
    symbol: "ден",
    name: "Macedonian Denar",
    namePlural: "Macedonian denari",
    decimalDigits: 2,
    rounding: 0,
    locale: "mk-MK",
    symbolPosition: "after",
    spaceBetween: true,
  },
  {
    code: "MMK",
    symbol: "K",
    name: "Myanma Kyat",
    namePlural: "Myanma kyats",
    decimalDigits: 0,
    rounding: 0,
    locale: "my-MM",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "MNT",
    symbol: "₮",
    name: "Mongolian Tugrik",
    namePlural: "Mongolian tugriks",
    decimalDigits: 0,
    rounding: 0,
    locale: "mn-MN",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "MOP",
    symbol: "MOP$",
    name: "Macanese Pataca",
    namePlural: "Macanese patacas",
    decimalDigits: 2,
    rounding: 0,
    locale: "zh-MO",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "MRU",
    symbol: "UM",
    name: "Mauritanian Ouguiya",
    namePlural: "Mauritanian ouguiyas",
    decimalDigits: 2,
    rounding: 0,
    locale: "ar-MR",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "MUR",
    symbol: "Rs",
    name: "Mauritian Rupee",
    namePlural: "Mauritian rupees",
    decimalDigits: 0,
    rounding: 0,
    locale: "en-MU",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "MVR",
    symbol: "Rf",
    name: "Maldivian Rufiyaa",
    namePlural: "Maldivian rufiyaas",
    decimalDigits: 2,
    rounding: 0,
    locale: "dv-MV",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "MWK",
    symbol: "MK",
    name: "Malawian Kwacha",
    namePlural: "Malawian kwachas",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-MW",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "MXN",
    symbol: "$",
    name: "Mexican Peso",
    namePlural: "Mexican pesos",
    decimalDigits: 2,
    rounding: 0,
    locale: "es-MX",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "MYR",
    symbol: "RM",
    name: "Malaysian Ringgit",
    namePlural: "Malaysian ringgits",
    decimalDigits: 2,
    rounding: 0,
    locale: "ms-MY",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "MZN",
    symbol: "MT",
    name: "Mozambican Metical",
    namePlural: "Mozambican meticals",
    decimalDigits: 2,
    rounding: 0,
    locale: "pt-MZ",
    symbolPosition: "before",
    spaceBetween: false,
  },

  {
    code: "NAD",
    symbol: "$",
    name: "Namibian Dollar",
    namePlural: "Namibian dollars",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-NA",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "NGN",
    symbol: "₦",
    name: "Nigerian Naira",
    namePlural: "Nigerian nairas",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-NG",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "NIO",
    symbol: "C$",
    name: "Nicaraguan Córdoba",
    namePlural: "Nicaraguan córdobas",
    decimalDigits: 2,
    rounding: 0,
    locale: "es-NI",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "NOK",
    symbol: "kr",
    name: "Norwegian Krone",
    namePlural: "Norwegian kroner",
    decimalDigits: 2,
    rounding: 0,
    locale: "nb-NO",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "NPR",
    symbol: "रु.",
    symbolNative: "रु.",
    name: "Nepalese Rupee",
    namePlural: "Nepalese rupees",
    decimalDigits: 2,
    rounding: 0,
    locale: "ne-NP",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "NZD",
    symbol: "NZ$",
    name: "New Zealand Dollar",
    namePlural: "New Zealand dollars",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-NZ",
    symbolPosition: "before",
    spaceBetween: false,
  },

  {
    code: "OMR",
    symbol: "ر.ع.",
    name: "Omani Rial",
    namePlural: "Omani rials",
    decimalDigits: 3,
    rounding: 0,
    locale: "ar-OM",
    symbolPosition: "before",
    spaceBetween: true,
  },

  {
    code: "PAB",
    symbol: "B/.",
    name: "Panamanian Balboa",
    namePlural: "Panamanian balboas",
    decimalDigits: 2,
    rounding: 0,
    locale: "es-PA",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "PEN",
    symbol: "S/",
    name: "Peruvian Nuevo Sol",
    namePlural: "Peruvian nuevos soles",
    decimalDigits: 2,
    rounding: 0,
    locale: "es-PE",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "PGK",
    symbol: "K",
    name: "Papua New Guinean Kina",
    namePlural: "Papua New Guinean kina",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-PG",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "PHP",
    symbol: "₱",
    name: "Philippine Peso",
    namePlural: "Philippine pesos",
    decimalDigits: 2,
    rounding: 0,
    locale: "fil-PH",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "PKR",
    symbol: "Rs",
    symbolNative: "روپیہ",
    name: "Pakistani Rupee",
    namePlural: "Pakistani rupees",
    decimalDigits: 0,
    rounding: 0,
    locale: "ur-PK",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "PLN",
    symbol: "zł",
    name: "Polish Zloty",
    namePlural: "Polish zlotys",
    decimalDigits: 2,
    rounding: 0,
    locale: "pl-PL",
    symbolPosition: "after",
    spaceBetween: true,
  },
  {
    code: "PYG",
    symbol: "₲",
    name: "Paraguayan Guarani",
    namePlural: "Paraguayan guaranis",
    decimalDigits: 0,
    rounding: 0,
    locale: "es-PY",
    symbolPosition: "before",
    spaceBetween: true,
  },

  {
    code: "QAR",
    symbol: "ر.ق",
    name: "Qatari Rial",
    namePlural: "Qatari rials",
    decimalDigits: 2,
    rounding: 0,
    locale: "ar-QA",
    symbolPosition: "before",
    spaceBetween: true,
  },

  {
    code: "RON",
    symbol: "lei",
    name: "Romanian Leu",
    namePlural: "Romanian lei",
    decimalDigits: 2,
    rounding: 0,
    locale: "ro-RO",
    symbolPosition: "after",
    spaceBetween: true,
  },
  {
    code: "RSD",
    symbol: "дин.",
    name: "Serbian Dinar",
    namePlural: "Serbian dinars",
    decimalDigits: 0,
    rounding: 0,
    locale: "sr-RS",
    symbolPosition: "after",
    spaceBetween: true,
  },
  {
    code: "RUB",
    symbol: "₽",
    symbolNative: "руб",
    name: "Russian Ruble",
    namePlural: "Russian rubles",
    decimalDigits: 2,
    rounding: 0,
    locale: "ru-RU",
    symbolPosition: "after",
    spaceBetween: true,
  },
  {
    code: "RWF",
    symbol: "RF",
    name: "Rwandan Franc",
    namePlural: "Rwandan francs",
    decimalDigits: 0,
    rounding: 0,
    locale: "rw-RW",
    symbolPosition: "before",
    spaceBetween: false,
  },

  {
    code: "SAR",
    symbol: "ر.س",
    symbolNative: "﷼",
    name: "Saudi Riyal",
    namePlural: "Saudi riyals",
    decimalDigits: 2,
    rounding: 0,
    locale: "ar-SA",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "SBD",
    symbol: "$",
    name: "Solomon Islands Dollar",
    namePlural: "Solomon Islands dollars",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-SB",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "SCR",
    symbol: "Rs",
    name: "Seychellois Rupee",
    namePlural: "Seychellois rupees",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-SC",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "SDG",
    symbol: "ج.س.",
    name: "Sudanese Pound",
    namePlural: "Sudanese pounds",
    decimalDigits: 2,
    rounding: 0,
    locale: "ar-SD",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "SEK",
    symbol: "kr",
    name: "Swedish Krona",
    namePlural: "Swedish kronor",
    decimalDigits: 2,
    rounding: 0,
    locale: "sv-SE",
    symbolPosition: "after",
    spaceBetween: true,
  },
  {
    code: "SGD",
    symbol: "S$",
    name: "Singapore Dollar",
    namePlural: "Singapore dollars",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-SG",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "SHP",
    symbol: "£",
    name: "Saint Helena Pound",
    namePlural: "Saint Helena pounds",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-SH",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "SLL",
    symbol: "Le",
    name: "Sierra Leonean Leone",
    namePlural: "Sierra Leonean leones",
    decimalDigits: 0,
    rounding: 0,
    locale: "en-SL",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "SOS",
    symbol: "Sh",
    name: "Somali Shilling",
    namePlural: "Somali shillings",
    decimalDigits: 0,
    rounding: 0,
    locale: "so-SO",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "SRD",
    symbol: "$",
    name: "Surinamese Dollar",
    namePlural: "Surinamese dollars",
    decimalDigits: 2,
    rounding: 0,
    locale: "nl-SR",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "SSP",
    symbol: "£",
    name: "South Sudanese Pound",
    namePlural: "South Sudanese pounds",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-SS",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "STN",
    symbol: "Db",
    name: "São Tomé and Príncipe Dobra",
    namePlural: "São Tomé and Príncipe dobras",
    decimalDigits: 2,
    rounding: 0,
    locale: "pt-ST",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "SYP",
    symbol: "£",
    name: "Syrian Pound",
    namePlural: "Syrian pounds",
    decimalDigits: 0,
    rounding: 0,
    locale: "ar-SY",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "SZL",
    symbol: "L",
    name: "Swazi Lilangeni",
    namePlural: "Swazi emalangeni",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-SZ",
    symbolPosition: "before",
    spaceBetween: false,
  },

  {
    code: "THB",
    symbol: "฿",
    name: "Thai Baht",
    namePlural: "Thai baht",
    decimalDigits: 2,
    rounding: 0,
    locale: "th-TH",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "TJS",
    symbol: "ЅМ",
    name: "Tajikistani Somoni",
    namePlural: "Tajikistani somonis",
    decimalDigits: 2,
    rounding: 0,
    locale: "tg-TJ",
    symbolPosition: "after",
    spaceBetween: true,
  },
  {
    code: "TMT",
    symbol: "m",
    name: "Turkmenistani Manat",
    namePlural: "Turkmenistani manat",
    decimalDigits: 2,
    rounding: 0,
    locale: "tk-TM",
    symbolPosition: "after",
    spaceBetween: true,
  },
  {
    code: "TND",
    symbol: "د.ت",
    name: "Tunisian Dinar",
    namePlural: "Tunisian dinars",
    decimalDigits: 3,
    rounding: 0,
    locale: "ar-TN",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "TOP",
    symbol: "T$",
    name: "Tongan Paʻanga",
    namePlural: "Tongan paʻanga",
    decimalDigits: 2,
    rounding: 0,
    locale: "to-TO",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "TRY",
    symbol: "₺",
    name: "Turkish Lira",
    namePlural: "Turkish Lira",
    decimalDigits: 2,
    rounding: 0,
    locale: "tr-TR",
    symbolPosition: "after",
    spaceBetween: true,
  },
  {
    code: "TTD",
    symbol: "$",
    name: "Trinidad and Tobago Dollar",
    namePlural: "Trinidad and Tobago dollars",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-TT",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "TWD",
    symbol: "NT$",
    symbolNative: "NT$",
    name: "New Taiwan Dollar",
    namePlural: "New Taiwan dollars",
    decimalDigits: 2,
    rounding: 0,
    locale: "zh-TW",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "TZS",
    symbol: "TSh",
    name: "Tanzanian Shilling",
    namePlural: "Tanzanian shillings",
    decimalDigits: 0,
    rounding: 0,
    locale: "sw-TZ",
    symbolPosition: "before",
    spaceBetween: false,
  },

  {
    code: "UAH",
    symbol: "₴",
    name: "Ukrainian Hryvnia",
    namePlural: "Ukrainian hryvnias",
    decimalDigits: 2,
    rounding: 0,
    locale: "uk-UA",
    symbolPosition: "after",
    spaceBetween: true,
  },
  {
    code: "UGX",
    symbol: "USh",
    name: "Ugandan Shilling",
    namePlural: "Ugandan shillings",
    decimalDigits: 0,
    rounding: 0,
    locale: "en-UG",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "USD",
    symbol: "$",
    name: "United States Dollar",
    namePlural: "US dollars",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-US",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "UYU",
    symbol: "$",
    name: "Uruguayan Peso",
    namePlural: "Uruguayan pesos",
    decimalDigits: 2,
    rounding: 0,
    locale: "es-UY",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "UZS",
    symbol: "сўм",
    name: "Uzbekistan Som",
    namePlural: "Uzbekistan som",
    decimalDigits: 0,
    rounding: 0,
    locale: "uz-UZ",
    symbolPosition: "after",
    spaceBetween: true,
  },

  {
    code: "VES",
    symbol: "Bs.S",
    name: "Venezuelan Bolívar Soberano",
    namePlural: "Venezuelan bolívars soberanos",
    decimalDigits: 2,
    rounding: 0,
    locale: "es-VE",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "VND",
    symbol: "₫",
    name: "Vietnamese Dong",
    namePlural: "Vietnamese dong",
    decimalDigits: 0,
    rounding: 0,
    locale: "vi-VN",
    symbolPosition: "after",
    spaceBetween: true,
  },
  {
    code: "VUV",
    symbol: "Vt",
    name: "Vanuatu Vatu",
    namePlural: "Vanuatu vatus",
    decimalDigits: 0,
    rounding: 0,
    locale: "en-VU",
    symbolPosition: "before",
    spaceBetween: false,
  },

  {
    code: "WST",
    symbol: "T",
    name: "Samoan Tala",
    namePlural: "Samoan tala",
    decimalDigits: 2,
    rounding: 0,
    locale: "sm-WS",
    symbolPosition: "before",
    spaceBetween: false,
  },

  {
    code: "XAF",
    symbol: "FCFA",
    name: "CFA Franc BEAC",
    namePlural: "CFA francs BEAC",
    decimalDigits: 0,
    rounding: 0,
    locale: "fr-CM",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "XCD",
    symbol: "$",
    name: "East Caribbean Dollar",
    namePlural: "East Caribbean dollars",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-AG",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "XOF",
    symbol: "CFA",
    name: "CFA Franc BCEAO",
    namePlural: "CFA francs BCEAO",
    decimalDigits: 0,
    rounding: 0,
    locale: "fr-SN",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "XPF",
    symbol: "₣",
    name: "CFP Franc",
    namePlural: "CFP francs",
    decimalDigits: 0,
    rounding: 0,
    locale: "fr-PF",
    symbolPosition: "before",
    spaceBetween: false,
  },

  {
    code: "YER",
    symbol: "ر.ي",
    name: "Yemeni Rial",
    namePlural: "Yemeni rials",
    decimalDigits: 0,
    rounding: 0,
    locale: "ar-YE",
    symbolPosition: "before",
    spaceBetween: true,
  },

  {
    code: "ZAR",
    symbol: "R",
    name: "South African Rand",
    namePlural: "South African rand",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-ZA",
    symbolPosition: "before",
    spaceBetween: true,
  },
  {
    code: "ZMW",
    symbol: "ZK",
    name: "Zambian Kwacha",
    namePlural: "Zambian kwachas",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-ZM",
    symbolPosition: "before",
    spaceBetween: false,
  },
  {
    code: "ZWL",
    symbol: "$",
    name: "Zimbabwean Dollar",
    namePlural: "Zimbabwean dollars",
    decimalDigits: 2,
    rounding: 0,
    locale: "en-ZW",
    symbolPosition: "before",
    spaceBetween: false,
  },
];

// Helper function to find currency by code
export const getCurrencyByCode = (code: string): Currency | undefined => {
  return CURRENCIES.find((c) => c.code === code);
};

// Popular currencies for quick access
export const POPULAR_CURRENCIES = [
  "USD",
  "EUR",
  "GBP",
  "JPY",
  "CNY",
  "INR",
  "NPR",
  "AUD",
  "CAD",
  "CHF",
];
